export const unifiedWords = {
  A: [{ word: 'Angry', image: '😠' }, { word: 'Ant', image: '🐜' }],
  B: [{ word: 'Bone', image: '🦴' }, { word: 'Big', image: '🦖' }],
  C: [{ word: 'Claw', image: '🦖' }, { word: 'Cave', image: '🕳️' }],
  D: [{ word: 'Dino', image: '🦕' }, { word: 'Dig', image: '⛏️' }],
  E: [{ word: 'Egg', image: '🥚' }, { word: 'Eat', image: '😋' }],
  F: [{ word: 'Fern', image: '🌿' }, { word: 'Fly', image: '🕊️' }],
  G: [{ word: 'Gas', image: '💨' }, { word: 'Giant', image: '🦕' }],
  H: [{ word: 'Horn', image: '/src/assets/trike.png' }, { word: 'Hot', image: '🔥' }],
  I: [{ word: 'Ice', image: '🧊' }, { word: 'Ink', image: '✒️' }],
  J: [{ word: 'Jungle', image: '🌴' }, { word: 'Jump', image: '🕴️' }],
  K: [{ word: 'King', image: '👑' }, { word: 'Kid', image: '🧒' }],
  L: [{ word: 'Lava', image: '🌋' }, { word: 'Leaf', image: '🍃' }],
  M: [{ word: 'Mud', image: '🟫' }, { word: 'Meat', image: '🍖' }],
  N: [{ word: 'Nest', image: '🪹' }, { word: 'Nod', image: '😴' }],
  O: [{ word: 'Old', image: '🐚' }, { word: 'Owl', image: '🦉' }],
  P: [{ word: 'Peak', image: '⛰️' }, { word: 'Plant', image: '🌱' }],
  Q: [{ word: 'Quake', image: '🌋' }],
  R: [{ word: 'Rex', image: '🦖' }, { word: 'Rock', image: '🪨' }],
  S: [{ word: 'Stomp', image: '👣' }, { word: 'Spike', image: '/src/assets/stego.png' }],
  T: [{ word: 'Trex', image: '🦖' }, { word: 'Tail', image: '🦎' }],
  U: [{ word: 'Up', image: '🔼' }, { word: 'Use', image: '👍' }],
  V: [{ word: 'Vine', image: '🌿' }, { word: 'Volcano', image: '🌋' }],
  W: [{ word: 'Wing', image: '🪶' }, { word: 'Wild', image: '🌳' }],
  X: [{ word: 'Box', image: '📦' }, { word: 'Fox', image: '🦊' }],
  Y: [{ word: 'Yak', image: '🐃' }, { word: 'Yum', image: '😋' }],
  Z: [{ word: 'Zip', image: '🤐' }, { word: 'Zoo', image: '🦓' }],
}; 